const TextContentType = {
  NAME: __SF_UITextContentTypeName,
  NAMEPREFIX: __SF_UITextContentTypeNamePrefix,
  GIVENNAME: __SF_UITextContentTypeGivenName,
  MIDDLENAME: __SF_UITextContentTypeMiddleName,
  FAMILYNAME: __SF_UITextContentTypeFamilyName,
  NAMESUFFIX: __SF_UITextContentTypeNameSuffix,
  NICKNAME: __SF_UITextContentTypeNickname,
  JOBTITLE: __SF_UITextContentTypeJobTitle,
  ORGANIZATIONNAME: __SF_UITextContentTypeOrganizationName,
  LOCATION: __SF_UITextContentTypeLocation,
  FULLSTREETADDRESS: __SF_UITextContentTypeFullStreetAddress,
  STREETADDRESSLINE1: __SF_UITextContentTypeStreetAddressLine1,
  STREETADDRESSLINE2: __SF_UITextContentTypeStreetAddressLine2,
  ADDRESSCITY: __SF_UITextContentTypeAddressCity,
  ADDRESSSTATE: __SF_UITextContentTypeAddressState,
  ADDRESSCITYANDSTATE: __SF_UITextContentTypeAddressCityAndState,
  SUBLOCALITY: __SF_UITextContentTypeSublocality,
  COUNTRYNAME: __SF_UITextContentTypeCountryName,
  POSTALCODE: __SF_UITextContentTypePostalCode,
  TELEPHONENUMBER: __SF_UITextContentTypeTelephoneNumber,
  EMAILADDRESS: __SF_UITextContentTypeEmailAddress,
  URL: __SF_UITextContentTypeURL,
  CREDITCARDNUMBER: __SF_UITextContentTypeCreditCardNumber,
  USERNAME: __SF_UITextContentTypeUsername,
  PASSWORD: __SF_UITextContentTypePassword,
  NEWPASSWORD: __SF_UITextContentTypeNewPassword,
  ONETIMECODE: __SF_UITextContentTypeOneTimeCode
};

export default TextContentType;
