import KeyboardType = require("./keyboardtype");

export declare const View: import("./view");
export declare const Label: import("./label");
export declare const TextAlignment: import("./textalignment");
export declare const ImageCacheType: import("./imagecachetype/imagecachetype");
export declare const Font: import("./font");
export declare const Color: import("./color");
export declare const Button: import("./button");
export declare const ActivityIndicator: import("./activityindicator");
export declare const Switch: any;
export declare const AlertView: import("./alertview");
export declare const Page: import("./page");
export declare const Pages: any;
export declare const HeaderBarItem: import("./headerbaritem");
export declare const FlexLayout: import("./flexlayout");
export declare const Slider: any;
export declare const ImageView: import("./imageview");
export declare const Image: import("./image");
export declare const StatusBarStyle: import("./statusbarstyle/statusbarstyle");
export declare const TextBox: import("./textbox");
export declare const KeyboardAppearance: import("./keyboardappearance/keyboardappearance");
export declare const ActionKeyType: import("./actionkeytype/actionkeytype");
export declare const ListView: import("./listview");
export declare const ListViewItem: import("./listviewitem");
export declare const ScrollView: import("./scrollview");
export declare const MapView: import("./mapview");
export declare const DatePicker: import("./datepicker");
export declare const Menu: import("./menu");
export declare const MenuItem: import("./menuitem");
export declare const SliderDrawer: any;
export declare const VideoView: any;
export declare const Quicklook: import("./quicklook");
export declare const Picker: import("./picker");
export declare const SearchView: import("./searchview");
export declare const Animator: import("./animator");
export declare const WebView: any;
export declare const TimePicker: any;
export declare const Dialog: import("./dialog");
export declare const BottomTabBar: import("./bottomtabbar");
export declare const TabBarItem: import("./tabbaritem");
export declare const Navigator: any;
export declare const SwipeView: any;
export declare const LayoutManager: import("./layoutmanager");
export declare const EmailComposer: import("./emailcomposer");
export declare const MaterialTextbox: import("./materialtextbox");
export declare const NavigationController: import("./navigationcontroller");
export declare const BottomTabBarController: import("./bottomtabbarcontroller");
export declare const ShimmerFlexLayout: any;
export declare const GifImage: import("./gifimage");
export declare const GifImageView: import("./gifimageview");
export declare const iOS: {
    DecelerationRate: import("./ios/decelerationrate/decelerationrate-iOS");
    ContentInsetAdjustment: import("./ios/contentinsetadjustment/contentinsetadjustment-iOS");
};
