module.exports = {
    View: require('./view'),
    Label: require('./label'),
    Style: require('./style.js'),
    TextAlignment : require('./textalignment.js'),
    Font: require('./font'),
    Color: require('./color'),
    Button: require('./button'),
    StateList: require('../util/statelist'),
    ActivityIndicator: require('./activityindicator'),
    Switch: require('./switch'),
    AlertView: require('./alertview').AlertView,
    AlertButtonType: require('./alertview').AlertButtonType,
    Page: require('./page'),
    Pages: require('./pages'),
    AbsoluteLayout: require('./absolutelayout'),
    Slider: require('./slider'),
    ListView: require('./listview'),
    ListViewController: require('./listviewcontroller'),
    ListViewItem: require('./listviewitem')
};